spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/booking_system?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
  jpa:
    properties:
      hibernate:
        dialect: ${DB_DIALECT:org.hibernate.dialect.MySQLDialect}
